version: '3'

services:

  # ----------------- #
  # Apache Spark      #
  # ----------------- #
  spark:
    image: docker.io/bitnami/spark:3.3
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    environment:
      - SPARK_MODE=master
    ports:
      - '8080:8080'
      - '4040:4040'
      - '7077:7077'
    volumes:
      - ./data:/data
      - ./src:/src
  spark-worker:
    image: docker.io/bitnami/spark:3.3
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_EXECUTOR_MEMORY=2G
      - SPARK_WORKER_CORES=2

    volumes:
      - ./data:/data
      - ./src:/src 
      - ./checkpoints:/opt/spark/checkpoints

  # ----------------- #
  # Apache Kafka      #
  # ----------------- #
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.3
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  # ----------------- #
  # Postgres          #
  # ----------------- #
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: sparkuser
      POSTGRES_PASSWORD: sparkpass
      POSTGRES_DB: sparkdb
    ports:
      - "5432:5432"

  # ----------------- #
  # Python Producer   #
  # ----------------- #
  producer:
    build: ./producer
    depends_on:
      - kafka
  
    # ----------------- #
  # Testes Unitários  #
  # ----------------- #
  pyspark-tests:
    build:
      context: .
      dockerfile: test/Dockerfile
    depends_on:
      - spark
    volumes:
      - ./src:/app/src
    working_dir: /app
    command: tail -f /dev/null